CREATE TABLE IF NOT EXISTS `#__fofcontent_contents` (
  `fofcontent_content_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `asset_id` INT(10) UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `slug` VARCHAR(255) NOT NULL,
  `fulltext` TEXT NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `catid` INT(10) UNSIGNED NOT NULL,
  `created_by` INT(11) UNSIGNED NOT NULL,
  `created_by_alias`VARCHAR(255) NULL,
  `created_on` DATE NOT NULL,
  `modified_by` INT(11) UNSIGNED NOT NULL,
  `modified_on` DATE NOT NULL,
  `locked_by` INT(11) UNSIGNED NOT NULL,
  `locked_on` DATETIME NOT NULL,
  `publish_up` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `publish_down` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `images` TEXT NULL,
  `urls` TEXT NULL,
  `attribs` VARCHAR(5120) NULL,
  `version` INT(10) UNSIGNED NOT NULL DEFAULT '1',
  `ordering` INT(11) NOT NULL,
  `metakey` TEXT NULL,
  `metadesc` TEXT NULL,
  `access` INT(10) UNSIGNED NOT NULL,
  `hits` INT(11) UNSIGNED NULL,
  `metadata` TEXT NULL,
  `language` CHAR(7) NOT NULL,
  `featured` TINYINT(3) UNSIGNED NOT NULL,
  PRIMARY KEY ( `fofcontent_content_id` )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
